<a href="https://colab.research.google.com/github/Metopher/Learning_ML-DL/blob/main/00_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#yea this is my first time learnign tensor flow nadanna naddannu

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim #no of dimensions idk tbh

0

In [ ]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim #so its actually the dimensions like a matrix

1

In [ ]:
matrix = tf.constant([[10,7],[6,7]])

In [ ]:
matrix.ndim

2

In [ ]:
another_matrix = tf.constant([[10.,5.],[5.,10.]],dtype =tf.float64)
another_matrix

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[10.,  5.],
       [ 5., 10.]])>

In [ ]:
another_matrix.ndim

2

In [ ]:
tensor = tf.constant([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
tensor


<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]], dtype=int32)>

In [ ]:
tensor.ndim #tensors can have alot of dimensions

3

In [ ]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
## Creating random tensor type shi


### Creating random tensor type shi

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(32)
random_2 = random_2.normal(shape=(3,2))
random_1,random_2, random_1== random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.7901182,  1.585549 ],
        [ 0.4356279,  0.2364518],
        [-0.1589871,  1.302304 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [ ]:
# shuffle a tensor(the food example , we shoud make sure it does not just learn the spagetti)

not_shuffled= tf.constant([[10,7],[1,3],[2,4]])
not_shuffled.ndim

# going to shuffle

tf.random.shuffle(not_shuffled,seed=56)



<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  3],
       [ 2,  4],
       [10,  7]], dtype=int32)>

In [ ]:
tf.random.set_seed(10)
print(tf.random.uniform([1,5,3]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

tf.Tensor(
[[[0.644151   0.8082472  0.8976548 ]
  [0.6368902  0.6270969  0.9936013 ]
  [0.02359486 0.03668392 0.5860578 ]
  [0.5740315  0.09047401 0.5755553 ]
  [0.25272822 0.11045039 0.61225283]]], shape=(1, 5, 3), dtype=float32)
tf.Tensor([0.55478156], shape=(1,), dtype=float32)


In [ ]:
print(tf.random.uniform([1,5,3]))

tf.Tensor(
[[[0.28776777 0.53159165 0.6660836 ]
  [0.43517685 0.2712083  0.8262744 ]
  [0.41320777 0.62144256 0.5367851 ]
  [0.96463275 0.6266488  0.89379966]
  [0.75270236 0.38672495 0.45730412]]], shape=(1, 5, 3), dtype=float32)


### Tensor with numpy

In [ ]:
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32)
A=tf.constant(numpy_A, shape=(24))
A
#x=tf.constant(some_matrix)
#y=tf.constant(vector)

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

### getting info from tensor

In [ ]:
rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
print(rank_4_tensor.dtype)
print(rank_4_tensor.ndim)
print(rank_4_tensor.shape)
print(rank_4_tensor.shape[0])
print(rank_4_tensor.shape[-1])
print(tf.size(rank_4_tensor).numpy())
print(tf.size(rank_4_tensor).numpy())

<dtype: 'float32'>
4
(2, 3, 4, 5)
2
5
120
120


In [ ]:
tensor=tf.constant([[5,3],[3,1]])
tensor/5

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.6],
       [0.6, 0.2]])>

In [ ]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 30],
       [30, 10]], dtype=int32)>

### matrix multi

In [ ]:
print(tensor)

tf.Tensor(
[[5 3]
 [3 1]], shape=(2, 2), dtype=int32)


In [ ]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[34, 18],
       [18, 10]], dtype=int32)>

In [ ]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[34, 18],
       [18, 10]], dtype=int32)>

In [ ]:
import numpy as np

In [ ]:
a= np.array([[10,3],[5,3]])
b= np.array([[5,3,6],[3,3,5]])

In [ ]:
a @ b

array([[59, 39, 75],
       [34, 24, 45]])

In [ ]:
# 2 x 2 @ 2 x 3

In [ ]:
print(a)
print(tf.transpose(a))

[[10  3]
 [ 5  3]]
tf.Tensor(
[[10  5]
 [ 3  3]], shape=(2, 2), dtype=int64)


In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 3],
       [3, 1]], dtype=int32)>

In [ ]:
tensor_16=tf.cast(tensor, dtype=tf.float16)
tensor_16

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[5., 3.],
       [3., 1.]], dtype=float16)>

### tensoflow operations basic ones

In [ ]:
tensor= tf.constant([[10,3],[5,2]])

In [ ]:
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 13],
       [15, 12]], dtype=int32)>

In [ ]:
tensor_float=tf.cast(tensor,dtype=tf.float32)
tf.math.reduce_variance(tensor_float)

<tf.Tensor: shape=(), dtype=float32, numpy=9.5>

In [ ]:
tf.math.reduce_std(tensor_float)

<tf.Tensor: shape=(), dtype=float32, numpy=3.082206964492798>

In [ ]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])

In [ ]:
F


<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463667869567871>