<a href="https://colab.research.google.com/github/Metopher/Learning_ML-DL/blob/main/Fundamentals_of_Pytroch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.9.0+cu126


In [ ]:
torch.cuda.is_available()
torch.cuda.get_device_name(0)

'Tesla T4'

### creating a tensor

In [ ]:
#using empty
torch.empty(2,3)
#just shows already written values there

tensor([[1.6345e-38, 0.0000e+00, 1.2353e+28],
        [4.4285e-41, 2.5348e+34, 4.4285e-41]])

In [ ]:
# check type
type(torch.empty(1,2))

torch.Tensor

In [ ]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.rand(5,2)

tensor([[0.2200, 0.6342],
        [0.4986, 0.2625],
        [0.3190, 0.4388],
        [0.0579, 0.5141],
        [0.5278, 0.5696]])

In [ ]:
torch.manual_seed(1)

In [ ]:
torch.rand(2,3)

tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999]])

In [ ]:
torch.manual_seed(1)
torch.rand(2,3)

tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999]])

In [ ]:
torch.tensor([[1,2],[2,3]])

tensor([[1, 2],
        [2, 3]])

In [ ]:
torch.arange(0,28,2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26])

In [ ]:
x=torch.tensor([[1,5,3],[2,2,2]])

In [ ]:
torch.empty_like(x)

tensor([[3616445622929465956, 6068934943532199221, 3689075027773894961],
        [6500442718621282350, 7309453675965983778, 8315168162784306286]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
x

tensor([[1, 5, 3],
        [2, 2, 2]])

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
x.to(torch.float64)

tensor([[1., 5., 3.],
        [2., 2., 2.]], dtype=torch.float64)