<a href="https://colab.research.google.com/github/Metopher/Learning_ML-DL/blob/main/NN_module_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.netowrk=nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )
  def forward(self,features):
    out=self.netowrk(features)
    return out



In [28]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

#call model for forward pass
model(features)

tensor([[0.4676],
        [0.4676],
        [0.4676],
        [0.4676],
        [0.4766],
        [0.4676],
        [0.4806],
        [0.4676],
        [0.4676],
        [0.4750]], grad_fn=<SigmoidBackward0>)

In [24]:
model.linear1.weight

Parameter containing:
tensor([[ 0.3812, -0.3077, -0.2052,  0.3917, -0.0806],
        [ 0.0962, -0.4465, -0.1320,  0.3976, -0.2106],
        [ 0.2652,  0.4121,  0.1041, -0.2847, -0.2675]], requires_grad=True)

In [26]:
model.linear1.bias

Parameter containing:
tensor([0.2914, 0.1161, 0.2544], requires_grad=True)